CREATE DATABASE IF NOT EXISTS motos;
USE motos;

CREATE TABLE Motos (
    id INT NOT NULL AUTO_INCREMENT,
    modelo VARCHAR(50),
    marca INT,
    ano INT,
    categoria VARCHAR(50),
    codigo_fipe VARCHAR(50),
    preco_fipe INT,
    tipo_motor VARCHAR(50),
    cilindrada FLOAT,
    potencia_G VARCHAR(50),
    potencia_A VARCHAR(50),
    torque_G VARCHAR(50),
    torque_A VARCHAR(50),
    partida VARCHAR(50),
    refrigeracao VARCHAR(50),
    cambio VARCHAR(50),
    embreagem VARCHAR(50),
    suspensao_d VARCHAR(50),
    suspensao_t VARCHAR(50),
    tipo_freio VARCHAR(50),
    freio_d VARCHAR(50),
    freio_t VARCHAR(50),
    pneu_d VARCHAR(50),
    pneu_t VARCHAR(50),
    chassi VARCHAR(50),
    alt_assento INT,
    altura INT,
    comprimento INT,
    largura INT,
    dist_eixos INT,
    peso FLOAT,
    cap_carga FLOAT,
    vel_max INT,
    acel_100 FLOAT,
    combustivel VARCHAR(50),
    cod_combustivel INT,
    consumo_G INT,
    consumo_A INT,
    autonomia_G INT,
    autonomia_A INT,
    tanque FLOAT,
    aditional TEXT,
    PRIMARY KEY (id),
    CONSTRAINT fk_moto_marca FOREIGN KEY (marca) REFERENCES Marcas(id),
    UNIQUE KEY idx_modelo_ano (modelo, ano)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;