CREATE DATABASE IF NOT EXISTS motos;
USE motos;

CREATE TABLE IF NOT EXISTS fotos (
    id INT NOT NULL AUTO_INCREMENT,
    foto_path VARCHAR(500) NOT NULL,
    descricao VARCHAR(20) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE INDEX idx_foto_path (foto_path)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

